### ISSUE TITLE
Error when compiling a Haxe class: "Please don't add haxe/std to your classpath, instead set HAXE_STD_PATH env var"

### ISSUE THREAD

**Issue by fullofcaffeine** [paulfitz/haxe#6]
Hey!

I just checked out this repo on the `ruby5` in order to try it out.

I have the following test class:

``` haxe
  class Test {

     public static function main() {
       new Test();
     }

     public function new() {
       trace("Hi there");
     }
 }
```

I'm compiling with:

`haxe-ruby -main Test.hx -rb Test.rb`

(haxe-ruby being a symlink to the custom-compiled binary in order not to conflict with my main `haxe` bin)

But I get the following error:

`/usr/local/lib/haxe/std/Std.hx:23: characters 7-87 : Please don't add haxe/std to your classpath, instead set HAXE_STD_PATH env var`

If I edit this file and **remove** these lines:

``` haxe
 22 #if !(core_api || cross)
 23 #error "Please don't add haxe/std to your classpath, instead set HAXE_STD_PATH env var"
 24 #end
```

Source: http://collabshot.com/show/QcF5Sn

Then it works.

Do you know why the `Std.hx` has these lines and why it conflicts with the Haxe ruby binary?

My main `haxe` and `haxelib` installation is @ v 3.2.1, 3.2.0-rc.3 respectivelly.

Maybe it's because Haxe ruby is @ 3.2.0?

Cheers!

**Comment by paulfitz** [comment]
It sounds like you're getting cross-talk between haxe binaries and their respective library paths.  You can set HAXE_STD_PATH explicitly to avoid this.  For example, my haxe git checkout and build is in `$HOME/cvs/haxe`, and I invoke `haxe` with this script:

```
#!/bin/bash
HAXE_STD_PATH=$HOME/cvs/haxe/std $HOME/cvs/haxe/haxe "$@"
```

**Comment by fullofcaffeine** [comment]
Oh I see, so set it to point to the std path for this version. Will try it out. Thanks!
