### ISSUE TITLE
Can't compile anymore

### ISSUE THREAD

**Issue by fullofcaffeine** [paulfitz/haxe#7]
Hey there Paul,

I think that due to recent updates in the repos referenced as submodules, specifically `extlib`, it's not possible to compile this out-of-the-box anymore. Here's the error I get when running `make`:

```
File "zip.ml", line 77, characters 10-15:
Error: Multiple definition of the extension constructor name Error.
       Names must be unique in a given structure or signature.
make[1]: *** [zip.cmxa] Error 2
make: *** [libs] Error 2
```

Do you happen to have the old submodules cloned locally? Perhaps it's worth adding them as part of the repo?

**Comment by fullofcaffeine** [comment]
Ping...

**Comment by fullofcaffeine** [comment]
@Simn Could you give me a quick hand here? I'd say you know why this is failing. I just need some simple directions on where to look / what to do. I have a project that needs Ruby in the backend and the Ruby fork would really come in handy now. Thanks!

**Comment by paulfitz** [comment]
Sorry for missing this thread.  Just ran into the problem myself and googled it and found myself here :-).  I could get past it by removing a duplicate `exception Error of string * string * string` line in `libs/ziplib/zip.ml`.

**Comment by zaxebo1** [comment]
> Sorry for missing this thread. Just ran into the problem myself and googled it and found myself here :-).

lol. thats funny :-)

**Comment by fullofcaffeine** [comment]
@paulfitz Ah, no problem! Thanks a lot, Paul! Closing this now.
